# [!!] package.json -> homepage 要去掉
version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports: 
      - '3050:80'
    depends_on:
      - client