# [!!] package.json -> homepage 要去掉
version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - '80:3000'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ../ssl/:/etc/nginx/ssl/
    restart: always
    ports: 
      - '443:443'
    depends_on:
      - client